name : Release Slack Enabled Workflow
on:
  workflow_dispatch 
  
jobs :
  slack_notification_initial:
    runs-on: ubuntu-latest
    name:  Slack Initial Notification
    permissions:
       actions : read
       
    outputs: 
      build_version : ${{fromJSON(steps.version.outputs.content).monorepo}}
      branch : ${{steps.branch_name.outputs.branch}}
      
    steps:   
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Get Branch Name
      id: branch_name
      run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
      
    - name: Check if version.json file exists
      id: check-file
      uses : andstor/file-existence-action@v2
      with:
          files: "version.json"
          
    - name: Read version.json
      id: version
      if: steps.check-file.outputs.files_exists == 'true'
      uses: juliangruber/read-file-action@v1
      with:
        path: version.json
      
    - name : Notify Slack (InProgress)
      id : notify_slack
      if: steps.check-file.outputs.files_exists == 'true'
      env:
        SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: 'C058W67M0SC' # Test Channel Id
        payload: | 
                 {
                   "text": "Hey <!subteam^S014W2U4MPY>",
                   "attachments": [
                      {
                        "pretext": "*_WebApp ${{ fromJSON(steps.version.outputs.content).monorepo }}_*",
                        "color": "dbab09",
                        "fields": [
                          {
                            "title": "Deployment",
                            "short": true,
                            "value": "Inprogress"
                          },
                          {
                            "type" : "divider"
                          },

                            {
                             "title": "Repository",
                             "short": true,
                             "value": "${{github.repository}}"
                           },
                           {
                            "type" : "divider"
                          },
                         
                           {
                             "title" : "Branch",
                             "short" : true,
                             "value" : "${{steps.branch_name.outputs.branch}}"
                           },
                           {
                            "type" : "divider"
                          },
                          
                           {
                            "title": "Commit URL",
                            "short": true,
                            "value": "https://github.com/${{github.repository}}/commit/${{github.sha}}"
                          }
                        ]
                      }
                     ]
                  }
  greet :
     name : Greet Message
     runs-on : ubuntu-latest 
     steps : 
       - name : Say Hello
         run: echo "Hello !!"
         
  check:
    if: always()
    needs: [slack_notification_initial, greet]
    outputs :
      job-list : ${{steps.extract_job.outputs.job-list}}
    runs-on: ubuntu-latest

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        id : extract_job
        run : |
           echo "::set-output name=job-list::slack_notification_initial,greet"
  
  print:
     name : Print Message
     runs-on : ubuntu-latest
     needs : check
     steps:
       - name : Access Jobs List
         run : "Job List : ${{toJSON(needs)}}"
 
