name : Release Workflow
on:
 push:
   branches:
     - release/*
jobs: 
  greet:
    name : Print Message
    runs-on : ubuntu-latest
    
    steps : 
      - name : Say Hello
        run: echo "Success"
       
