name : Release Workflow
on:
 push:
   branches:
     - master
jobs: 
  greet:
    name : Print Message
    runs-on : ubuntu-latest
    
    steps : 
      - name : Say Hello
        run: echo "Hello 1"
       
