name : Release Workflow
on:
 push:
   branches:
     - release/*
 workflow_dispatch:    
jobs: 
  greet:
    name : Print Message
    runs-on : ubuntu-latest
    
    steps : 
      - name : Say Hello
        run: echo "${GITHUB_REF#refs/heads/}"
       
