name : Release Workflow

on:
  workflow_dispatch
  
jobs: 
  slack_notification: 
    runs-on: ubuntu-latest
    name:  Notify Slack
    permissions:
       actions : read
    steps:   
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Get Branch Name
      id: branch_name
      run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
      
    - name: Check if version.json file exists
      id: check-file
      uses : andstor/file-existence-action@v2
      with:
          files: "version.json"
          
    - name: Read version.json
      id: version
      if: steps.check-file.outputs.files_exists == 'true'
      uses: juliangruber/read-file-action@v1
      with:
        path: version.json
      
    - name : Notify Slack (InProgress)
      id : notify_slack
      if: steps.check-file.outputs.files_exists == 'true'
      env:
        SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: 'C058W67M0SC' # Test Channel Id
        payload: | 
                 {
                   "text": "Hey <!subteam^S014W2U4MPY>",
                   "attachments": [
                      {
                        "pretext": "*_WebApp ${{ fromJSON(steps.version.outputs.content).monorepo }}_*",
                        "color": "dbab09",
                        "fields": [
                          {
                            "title": "Deployment",
                            "short": true,
                            "value": "Inprogress"
                          },
                          {
                            "type" : "divider"
                          },

                            {
                             "title": "Repository",
                             "short": true,
                             "value": "${{github.repository}}"
                           },
                           {
                            "type" : "divider"
                          },
                         
                           {
                             "title" : "Branch",
                             "short" : true,
                             "value" : "${{steps.branch_name.outputs.branch}}"
                           },
                           {
                            "type" : "divider"
                          },
                          
                           {
                            "title": "Commit URL",
                            "short": true,
                            "value": "https://github.com/${{github.repository}}/commit/${{github.sha}}"
                          }
                        ]
                      }
                     ]
                  }
    - name : Save Slack Outputs
      env:
        SLACK_NOTIFICATION_OUTPUT : ${{steps.notify_slack.outputs}}
  greet:
    name : Print Message
    runs-on : ubuntu-latest
    
    steps : 
      - name : Say Hello
        run: echo "Hello There"
       
