on: 
   workflow_dispatch:

jobs:
  post_message:
    runs-on: ubuntu-latest
    name: Console Message
    steps:
      - run: echo "Hello World"
        shell : bash
  new_push_job:
    runs-on: ubuntu-latest
    name: New push to repo
    if: always()
    needs : [post_message]
    steps:   
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Check if version.json file exists
      id: check-file
      uses : andstor/file-existence-action@v2
      with:
          files: "version.json"
          
    - name: Read version.json
      id: version
      if: steps.check-file.outputs.files_exists == 'true'
      uses: juliangruber/read-file-action@v1
      with:
        path: version.json
        
    - uses : technote-space/workflow-conclusion-action@v3 
    
    - name: Send Slack Notification
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: 'C058W67M0SC' # ID of Slack Channel you want to post to
        payload: | 
                 {
                   "text": "Hey <!subteam^S014W2U4MPY>",
                   "attachments": [
                      {
                        "pretext": "*_WebApp ${{ fromJSON(steps.version.outputs.content).monorepo }}_* is in Staging",
                        "color": "28a745",
                        "fields": [
                          {
                            "title": "Status",
                            "short": true,
                            "value": "${{env.WORKFLOW_CONCLUSION}}"
                          }
                        ]
                      }
                     ]
                  }        
      env:
        SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
