on: 
   workflow_dispatch:

jobs:
  post_message:
    runs-on: ubuntu-latest
    name: Console Message
    steps:
      - run: exit 1
        shell : bash
  slack_notification:
    runs-on: ubuntu-latest
    name: Post Slack Notification
    if: always()
    needs : [post_message]
    steps:   
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Check if version.json file exists
      id: check-file
      uses : andstor/file-existence-action@v2
      with:
          files: "version.json"
          
    - name: Read version.json
      id: version
      if: steps.check-file.outputs.files_exists == 'true'
      uses: juliangruber/read-file-action@v1
      with:
        path: version.json
    - name : Workflow Conclusion
      id: workflow_conclusion 
      uses : technote-space/workflow-conclusion-action@v3
    - name: Iterate
      run: | 
            echo "Workflow Name: ${{ github.workflow }}"
            echo "Event Name: ${{ github.event_name }}"
           
    - name: Send Slack Success Notification
      if: ${{env.WORKFLOW_CONCLUSION == 'success'}}
      env:
        SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: 'C058W67M0SC' # ID of Slack Channel you want to post to
        payload: | 
                 {
                   "text": "Hey <!subteam^S014W2U4MPY>",
                   "attachments": [
                      {
                        "pretext": "*_WebApp ${{ fromJSON(steps.version.outputs.content).monorepo }}_* is in Staging! :rocket: :tada:",
                        "color": "28a745",
                        "fields": [
                          {
                            "title": "Deployment",
                            "short": true,
                            "value": "SUCCESS"
                          }
                        ]
                      }
                     ]
                  }
                  
    - name: Send Slack Failure Notification
      if: ${{env.WORKFLOW_CONCLUSION == 'failure'}}
      env:
        SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
      uses: slackapi/slack-github-action@v1.23.0
      with:
         channel-id: 'C058W67M0SC' # ID of Slack Channel you want to post to
         payload: |
                  {
                    "text": "Hey <!subteam^S014W2U4MPY>",
                    "attachments" : [
                      {
                        "pretext": "",
                        "color": "FF0000",
                        "fields": [
                          {
                            "title": "Deployment",
                            "short": true,
                            "value": "FAIL"
                          }
                        ]
                      }
                    ]
                  }
