name : Slack Notification Workflow
on: 
   workflow_run: 
     workflows : ['Release Workflow']
     types:
       - completed

jobs:

  slack_notification:
    runs-on: ubuntu-latest
    name: Post Slack Notification
    steps:   
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Check if version.json file exists
      id: check-file
      uses : andstor/file-existence-action@v2
      with:
          files: "version.json"
          
    - name: Read version.json
      id: version
      if: steps.check-file.outputs.files_exists == 'true'
      uses: juliangruber/read-file-action@v1
      with:
        path: version.json
    - name : Jobs API
      id : jobs_id
      run : |
            curl -X GET ${{toJSON(github.event.workflow_run.jobs_url)}}
    - name : Print
      run : echo "${{steps.jobs_id.outputs}}"
    - name: Send Slack Success Notification
      if: ${{github.event.workflow_run.conclusion == 'success'}}
      env:
        SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: 'C058W67M0SC' # ID of Slack Channel you want to post to
        payload: | 
                 {
                   "text": "Hey <!subteam^S014W2U4MPY>",
                   "attachments": [
                      {
                        "pretext": "*_WebApp ${{ fromJSON(steps.version.outputs.content).monorepo }}_* is in Staging! :rocket: :tada:",
                        "color": "28a745",
                        "fields": [
                          {
                            "title": "Deployment",
                            "short": true,
                            "value": "SUCCESS"
                          }
                        ]
                      }
                     ]
                  }
                  
    - name: Send Slack Failure Notification
      if: ${{github.event.workflow_run.conclusion == 'failure'}}
      env:
        SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
      uses: slackapi/slack-github-action@v1.23.0
      with:
         channel-id: 'C058W67M0SC' # ID of Slack Channel you want to post to
         payload: |
                  {
                    "text": "Hey <!subteam^S014W2U4MPY>",
                    "attachments" : [
                      {
                        "pretext": "",
                        "color": "FF0000",
                        "fields": [
                          {
                            "title": "Deployment",
                            "short": true,
                            "value": "FAIL"
                          }
                        ]
                      }
                    ]
                  }
