name: Slack Notification
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
      
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: act10ns/slack@v1
      with:
    # For posting a rich message using Block Kit
         status: ${{job.status}}
         channel: '#hackathon'
      env:
          SLACK_WEBHOOK_URL : https://hooks.slack.com/services/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

