on: 
   workflow_dispatch:

jobs:
  post_message:
    runs-on: ubuntu-latest
    name: Console Message
    steps:
      - run: exit 1
        shell : bash
  new_push_job:
    runs-on: ubuntu-latest
    name: New push to repo
    if: always()
    needs : [post_message]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Check if version.json file exists
      id: check-file
      uses : andstor/file-existence-action@v2
      with:
          files: "version.json"
          
    - name: Read version.json
      id: version
      if: steps.check-file.outputs.files_exists == 'true'
      uses: juliangruber/read-file-action@v1
      with:
        path: version.json    
    - name: Send GitHub trigger payload to Slack Workflow Builder
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: 'C058W67M0SC' # ID of Slack Channel you want to post to
        payload: | 
                 {
                   "text": "Deployment finished (Completed) ${{ fromJSON(steps.version.outputs.content).monorepo }}",
                   "attachments": [
                      {
                        "pretext": "Deployment finished",
                        "color": "28a745",
                        "fields": [
                          {
                            "title": "Status",
                            "short": true,
                            "value": "${{jobs.conclusion}}"
                          }
                        ]
                      }
                     ]
                  }
      env:
        SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
