on: 
   workflow_dispatch:

jobs:
  new_push_job:
    runs-on: ubuntu-latest
    name: New push to repo
    steps:
    - name: Send GitHub trigger payload to Slack Workflow Builder
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: 'C058W67M0SC' # ID of Slack Channel you want to post to
        payload: | 
                 {
                   "text": "Deployment finished (Completed)",
                   "attachments": [
                   {
                     "pretext": "Deployment finished",
                     "color": "28a745",
                     "fields": [
                       {
                         "title": "Status",
                         "short": true,
                         "value": "Completed"
                       }
                     ]
                   }
                     ]
                  }
      env:
        SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
