name: Slack Deployment Pre Notification Workflow
on: 
   workflow_run: 
     workflows : ['Release Workflow']
     types:
       - requested


jobs:

  slack_pre_notification:

     runs-on: ubuntu-latest
     name: Notify Slack (Pre)
     permissions:
         actions : write
     steps:
        - name : Github Checkout Repository
          uses : actions/checkout@v3
          with : 
             fetch-depth : 0
             ref : ${{github.sha}}

        - name: Get Branch Name
          id: branch_name
          run: echo "::set-output name=branch::${{github.event.workflow_run.head_branch}}" 

        - name : Check if version.json file exists
          id   : check_file
          uses : andstor/file-existence-action@v2
          with : 
             files : "version.json"

        - name : Read version.json
          id : json_file
          if : steps.check_file.outputs.files_exists == 'true'
          uses : juliangruber/read-file-action@v1
          with : 
              path : version.json  
                       
        - name: Send Slack Notification (InProgress)
          id: slack_id
          uses: slackapi/slack-github-action@v1.24.0
          env:
             SLACK_BOT_TOKEN : ${{secrets.SLACK_BOT_TOKEN}}
          with:
             channel-id : 'C058W67M0SC' # ID of Slack Channel
             payload : |
                       {
                          "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                          "blocks": [
                            {
                              "type": "section",
                              "text": {
                                "type": "mrkdwn",
                                "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                              }
                            }
                          ]
                        }

        - name : Create Slack TS JSON
          run : |
                echo '${{toJSON(steps.slack_id.outputs)}}' > slack.json
                
        - name : Save Slack TS JSON
          uses: actions/upload-artifact@v3
          with:
            name: slack-artifact
            path: slack.json              

       