name: Slack Notification
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
      
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
    # For posting a rich message using Block Kit
          channel-id: 'C058K4JRMGR'
          slack-message : 'SUCCESS'
      env:
          SLACK_BOT_TOKEN : xoxp-5278384501347-5278520564786-5272093735142-cc71d2df992e990102344878f0713ab4
