name : Slack Notification Workflow
on: 
   workflow_run: 
     workflows : ['Release Workflow']
     types:
       - completed

jobs:

  slack_notification:
    runs-on: ubuntu-latest
    name: Notify Slack 
    permissions:
         actions : read
    steps:  
    - name : Jobs API
      if: ${{github.event.workflow_run.conclusion == 'failure'}}
      id : jobs_api
      run : |
           response=$(curl -s \
              -X GET \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{github.token}}"\
              ${{github.event.workflow_run.jobs_url}} | jq -r '.jobs' | jq -c .)
              
            echo "::set-output name=response::$response"
            
    - name : Get Failed Job
      id : failed_job
      run : |
            node -e '
            let job_reponse = {
              link : "",
              step : "",
              slackTs : ""
            }
            const jobs = JSON.parse(process.env.JOBS_API_RESPONSE);
            for(let {status,conclusion,html_url,steps} of jobs) {
              if(status === "completed" && conclusion === "failure") {
                job_reponse.link = html_url;
              };
              if(steps.length > 0) {
                for(let step of steps) {
                  if(step.conclusion === "failure") {
                    job_reponse.step = step.name;
                  };
                  
                  if(step.id === 'notify_slack') {
                    console.log("---Print Step---", step.outputs)
                  }
                }
              }
            }
            process.stdout.write(`::set-output name=job_reponse::${JSON.stringify(job_reponse)}`);
            '
      env:
          JOBS_API_RESPONSE: ${{steps.jobs_api.outputs.response}}
          
    - name: Send Slack Success Notification
      if: ${{github.event.workflow_run.conclusion == 'success'}}
      env:
        SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: 'C058W67M0SC' # Test Channel Id
        payload: | 
                 {
                   "text": "Hey <!subteam^S014W2U4MPY>",
                   "attachments": [
                      {
                        "pretext": "*_WebApp ${{ fromJSON(steps.version.outputs.content).monorepo }}_* is in Staging! :rocket: :tada:",
                        "color": "28a745",
                        "fields": [
                          {
                            "title": "Deployment",
                            "short": true,
                            "value": "Success"
                          },
                          {
                            "type" : "divider"
                          },

                            {
                             "title": "Repository",
                             "short": true,
                             "value": "${{github.repository}}"
                           },
                           {
                            "type" : "divider"
                          },
                         
                           {
                             "title" : "Branch",
                             "short" : true,
                             "value" : "${{steps.branch_name.outputs.branch}}"
                           },
                           {
                            "type" : "divider"
                          },
                          
                           {
                            "title": "Commit URL",
                            "short": true,
                            "value": "https://github.com/${{github.repository}}/commit/${{github.sha}}"
                          }
                        ]
                      }
                     ]
                  }
                  
    - name: Send Slack Failure Notification
      if: ${{github.event.workflow_run.conclusion == 'failure'}}
      env:
        SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
      uses: slackapi/slack-github-action@v1.24.0
      with:
         channel-id: 'C058W67M0SC' # test channel id
         payload: |
                  {
                    "text": "Hey <!subteam^S014W2U4MPY>",
                    "attachments" : [
                      {
                        "pretext": "",
                        "color": "FF0000",
                        "fields": [
                          {
                            "title": "Deployment",
                            "short": true,
                            "value": "Failed"
                          },
                          {
                            "type" : "divider"
                          },
                           {
                             "title": "Repository",
                             "short": true,
                             "value": "${{github.repository}}"
                           },
                           {
                            "type" : "divider"
                          },
                           {
                             "title" : "Branch",
                             "short" : true,
                             "value" : "${{steps.branch_name.outputs.branch}}"
                           },
                           {
                            "type" : "divider"
                          },
                           {
                             "title" : "Failed Step",
                             "short" : true,
                             "value" : "${{fromJSON(steps.failed_job.outputs.failed_job).step}}"
                           },
                            {
                            "type" : "divider"
                          },
                           {
                             "title": "Failed Job URL",
                             "short": true,
                             "value": "${{fromJSON(steps.failed_job.outputs.failed_job).link}}"
                           }
                        ]
                      }
                    ]
                  }
